function hB = plugin_board()
% Digilent ZYBO Z7 Board Registration

% Construct board object
hB = hdlcoder.Board;
hB.BoardName    = 'ZYBO Z7-20';

% FPGA device information
hB.FPGAVendor   = 'Xilinx';
hB.FPGAFamily   = 'Zynq';
hB.FPGADevice   = 'xc7z020';
hB.FPGAPackage  = 'clg400';
hB.FPGASpeed    = '-1';

% Tool information
hB.SupportedTool = {'Xilinx Vivado'};

% FPGA JTAG chain position
hB.JTAGChainPosition = 2;

%% Add interfaces
% Standard "External Port" interface
hB.addExternalPortInterface( ...
    'IOPadConstraint', {'IOSTANDARD = LVCMOS33'});

%% INPUTS

% Adds the push buttons as an external interface 
hB.addExternalIOInterface( ...
   'InterfaceID',    'Push Buttons', ...
   'InterfaceType',  'IN', ...
   'PortName',       'pushb', ...
   'PortWidth',      4, ...
   'FPGAPin',        {'K18', 'P16', 'K19', 'Y16'}, ...
   'IOPadConstraint', {'IOSTANDARD = LVCMOS33'});

% Adds the switches as an external interface 
hB.addExternalIOInterface( ...
   'InterfaceID',    'Switches', ...
   'InterfaceType',  'IN', ...
   'PortName',       'switch', ...
   'PortWidth',      4, ...
   'FPGAPin',        {'G15', 'P15', 'W13', 'T16'}, ...
   'IOPadConstraint', {'IOSTANDARD = LVCMOS33'});

%% OUTPUTS

% Adds the main 4 LEDs as an external interface
hB.addExternalIOInterface( ...
  'InterfaceID',    'LEDs General Purpose', ...
  'InterfaceType',  'OUT', ...
  'PortName',       'led', ...
  'PortWidth',      4, ...
  'FPGAPin',        {'M14', 'M15', 'G14', 'D18'}, ...
  'IOPadConstraint', {'IOSTANDARD = LVCMOS33'});

% Adds RGB LED 5 red channel as an external interface 
hB.addExternalIOInterface( ...
   'InterfaceID',    'RGB LED 5 red', ...
   'InterfaceType',  'OUT', ...
   'PortName',       'led5_r', ...
   'PortWidth',      1, ...
   'FPGAPin',        {'Y11'}, ...
   'IOPadConstraint', {'IOSTANDARD = LVCMOS33'});

% Adds RGB LED 5 green channel as an external interface 
hB.addExternalIOInterface( ...
   'InterfaceID',    'RGB LED 5 green', ...
   'InterfaceType',  'OUT', ...
   'PortName',       'led5_g', ...
   'PortWidth',      1, ...
   'FPGAPin',        {'T5'}, ...
   'IOPadConstraint', {'IOSTANDARD = LVCMOS33'});

% Adds RGB LED 5 blue channel as an external interface 
hB.addExternalIOInterface( ...
   'InterfaceID',    'RGB LED 5 blue', ...
   'InterfaceType',  'OUT', ...
   'PortName',       'led5_b', ...
   'PortWidth',      1, ...
   'FPGAPin',        {'Y12'}, ...
   'IOPadConstraint', {'IOSTANDARD = LVCMOS33'});

% Adds RGB LED 6 red channel as an external interface 
hB.addExternalIOInterface( ...
   'InterfaceID',    'RGB LED 6 red', ...
   'InterfaceType',  'OUT', ...
   'PortName',       'led6_r', ...
   'PortWidth',      1, ...
   'FPGAPin',        {'V16'}, ...
   'IOPadConstraint', {'IOSTANDARD = LVCMOS33'});

% Adds RGB LED 6 green channel as an external interface 
hB.addExternalIOInterface( ...
   'InterfaceID',    'RGB LED 6 green', ...
   'InterfaceType',  'OUT', ...
   'PortName',       'led6_g', ...
   'PortWidth',      1, ...
   'FPGAPin',        {'F17'}, ...
   'IOPadConstraint', {'IOSTANDARD = LVCMOS33'});

% Adds RGB LED 6 blue channel as an external interface 
hB.addExternalIOInterface( ...
   'InterfaceID',    'RGB LED 6 blue', ...
   'InterfaceType',  'OUT', ...
   'PortName',       'led6_b', ...
   'PortWidth',      1, ...
   'FPGAPin',        {'M17'}, ...
   'IOPadConstraint', {'IOSTANDARD = LVCMOS33'});
